  FILE DRIVER = 0d35cd8e-97ea-4f9a-96af-0f0d89f76567 {
#    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-0d35cd8e-97ea-4f9a-96af-0f0d89f76567/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-0d35cd8e-97ea-4f9a-96af-0f0d89f76567/section1.pe
    SECTION UI = "UFSDxe"
  }

  FILE DRIVER = 7a32bd23-f735-4f57-aa1a-447d2fe3be0d {
    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-7a32bd23-f735-4f57-aa1a-447d2fe3be0d/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-7a32bd23-f735-4f57-aa1a-447d2fe3be0d/section1.pe
    SECTION UI = "SPI"
  }

  FILE DRIVER = 2a7b4bef-80cd-49e1-b473-374ba4d673fc {
    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-2a7b4bef-80cd-49e1-b473-374ba4d673fc/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-2a7b4bef-80cd-49e1-b473-374ba4d673fc/section1.pe
    SECTION UI = "SPMI"
  }

  FILE DRIVER = 04de8591-d2b3-4077-bbbe-b12070094eb6 {
    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-04de8591-d2b3-4077-bbbe-b12070094eb6/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-04de8591-d2b3-4077-bbbe-b12070094eb6/section1.pe
    SECTION UI = "I2C"
  }

  FILE DRIVER = 3299a266-15f0-4346-8318-716336736d3e {
    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-3299a266-15f0-4346-8318-716336736d3e/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-3299a266-15f0-4346-8318-716336736d3e/section1.pe
    SECTION UI = "UsbDeviceDxe"
  }

  FILE DRIVER = 5af77f10-90df-4e7e-8325-a17ec09d5443 {
    SECTION DXE_DEPEX = workspace/proprietary/section0_extracted/volume-8/file-5af77f10-90df-4e7e-8325-a17ec09d5443/section0.dxe.depex
    SECTION PE32 = workspace/proprietary/section0_extracted/volume-8/file-5af77f10-90df-4e7e-8325-a17ec09d5443/section1.pe
    SECTION UI = "UsbMsdDxe"
  }
